### PR TITLE
Fix svelte 5 children typing issue

### LINKED ISSUE #74: A little issue with Svelte 5 typescript check
I'm trying it with Svelte 5 for the first time today and it works.

I'm having only a small issue:

```svelte
<script lang="ts">
    export let selectedDateTime: string | Date | Date[] | null | undefined = undefined;
    // ...
</script>

<Flatpickr on:change bind:value={selectedDateTime}>
    <!-- ... -->
</Flatpickr>
```

```
Error: Object literal may only specify known properties, and 'children' does not exist in type 'WithBindings<SvelteFlatpickrProps & SvelteInputProps>'. (ts)
```

Can you help me understand?

### PR DESCRIPTION
**Pull request by frederikhors**
Fixes https://github.com/jacobmischka/svelte-flatpickr/issues/74

### CODE REVIEW

**Comment by frederikhors** [comment]
@jacobmischka this is a quick fix to make the typescript error go away, but obviously there is more to do to type correctly.

I would be grateful if you would publish this PR with a new hotfix version.

**Comment by frederikhors** [comment]
@jacobmischka is there a problem with this PR?

**Comment by frederikhors** [comment]
@jacobmischka can you please release a patch version with this? Thanks a lot!

**Comment by frederikhors** [comment]
@jacobmischka can you please release a patch version with this? Thanks a lot!

**Comment by frederikhors** [comment]
@jacobmischka can you please release a patch version with this? Thanks a lot!

**Comment by frederikhors** [comment]
@jacobmischka can you please release a patch version with this? Thanks a lot!

**Comment by jacobmischka** [comment]
Oops so sorry... doing now

**Comment by jacobmischka** [comment]
@frederikhors I added you as a github collaborator if you're interested. I'll also add you to the npm package if you're interested and you let me know your npm username

**Pull request merged**
