### PR TITLE
allow custom element so that controls can be added

### PR DESCRIPTION
**Pull request by antony**
This is the v2 version of the code, and fixes https://github.com/jacobmischka/svelte-flatpickr/issues/9

I've not done a merge this complex before, so what I would propose is that we merge this and release 1.2.0, and then we can rebase master from it, and then do the v3 code.

Do you think that is the right way to approach this?

### CODE REVIEW

**Comment by jacobmischka** [comment]
I'd much rather not rebase, ha. Let me see if I can come up with something real quick, one second.

**Comment by jacobmischka** [comment]
Oh, you already made a v2 branch. I don't think we even need to rebase then, do we? Can't we just release 1.2.0 from v2 directly and not touch master?

**Comment by jacobmischka** [comment]
Oh, also, sorry, but this is a yarn project, please get that package-lock outta here :sunglasses:

**Comment by antony** [comment]
@jacobmischka Yeah, that's one way of managing it. We can do that instead if you prefer

Re yarn - it's ok, nobody is perfect :stuck_out_tongue_closed_eyes: . I'll remove the package lock ;)

**Comment by jacobmischka** [comment]
Cool, done and published to npm

**Comment by antony** [comment]
@jacobmischka I think you've forgotten to push the v1.x.x tag for this to github.

I need to make a fix for a race condition on initialisation, but I need the tag to do this :)

**Comment by antony** [comment]
Ok ignore above comment - not entirely sure what I was seeing here :) It's 1.2.0 I was looking for.

**Comment by jacobmischka** [comment]
Ha okay cool. Sorry for the delay on my end, I deployed that from my laptop and I actually haven't been on it to check for the tag in a few days.

**Pull request merged**
