### PR TITLE
upgrade to svelte v2 + Flatpickr 4.5.2

### PR DESCRIPTION
**Pull request by antony**

### CODE REVIEW

**Comment by jacobmischka** [comment]
Thanks! :tada:

**Comment by jacobmischka** [comment]
Because this project uses yarn, not npm. And yeah I realized that yarn.lock didn't get updated, but I'll do that one of these days, ha.

**Comment by jacobmischka** [comment]
I don't believe that's correct, the lockfile is only used for the top-level project, not for dependencies. But in either case this package uses yarn for its lockfile, and using both at the same time isn't a good idea as they'll often conflict.

Thanks again for the pull request!

**Comment by antony** [comment]
Perhaps my understanding is wrong then - no problems :)

**Pull request merged**
