### PR TITLE
check value, in addition to fp and ready, before calling fp.setDate.

### PR DESCRIPTION
**Pull request by mchant**

### CODE REVIEW

**Comment by jacobmischka** [comment]
I don't think this is correct, you would never be able to set the value to anything falsey. Do you have any more information about why this change should be made?

**Comment by mchant** [comment]
When I use date range, I get this error:
```
TypeError: fp.setDate is not a function
    at Object.$$self.$$.update (Flatpickr.svelte? [sm]:29:10)
    at update (index.mjs:1081:12)
    at flush (index.mjs:1052:13)
```
When I put a debugger to inspect fp, I see that fp is an array so the error makes sense
```
fp
(2) [{…}, {…}]
0: {l10n: {…}, _handlers: Array(0), pluginElements: Array(0), loadedPlugins: Array(0), parseDate: ƒ, …}
1: {l10n: {…}, _handlers: Array(0), pluginElements: Array(0), loadedPlugins: Array(0), parseDate: ƒ, …}
length: 2
[[Prototype]]: Array(0)
```
Each item in the array had value=''.

One thought was to check if fp is an object instead of array, but I noticed I don't get the error if I check for `&& value`, so I submitted that one as a fix.

Let me know your thoughts. Maybe it's better to check if fp is an object.

**Comment by jacobmischka** [comment]
Can you post your flatpickr config object please?

**Comment by mchant** [comment]
```
{
    element: `#flatpickr_${Math.floor(Math.random() * 100)}`,
    allowInput: true,
    mode: 'range'
  }
```

**Comment by jacobmischka** [comment]
Okay, can I actually see more of your whole usage of the component? I don't know what the `element` option is doing, I've never seen that before and it's not documented anywhere that I can see. I don't know why `fp` is an array, it shouldn't be, so I think you're doing something else that's making this behave weirdly.

**Comment by mchant** [comment]
The behavior was strange before too. The problem doesn't show up every time. Pressing f5 sometimes made the error go away. Below is the implementation.

final component (with things removed except items used for DateRangePicker) is:
  ```
<script>
import DateRangePicker from '../../components/Pickers/DateRange.svelte'
const handleDateRange = (event) => {
    // just sets a variable
    const [selectedDates, dateStr] = event.detail
    const date_range = dateStr.replace(/\s+/g, '').split('to')
  }
</script>
<DateRangePicker on:change={handleDateRange} />
```

DateRangePicker component being called is:
```
<script>
  import Picker from './FlatPicker.svelte'
  export let value
  let options = {
    mode: 'range',
  }
</script>

<Picker {value} {options} on:change />
```

FlatPicker component being called is:
```
<script>
  import Flatpickr from 'svelte-flatpickr'
  import { createEventDispatcher } from 'svelte'
  import { TextInput } from 'carbon-components-svelte'
  import 'flatpickr/dist/flatpickr.css'
  import 'flatpickr/dist/themes/light.css'

  const dispatch = createEventDispatcher()
  export let value = null
  export let options = {}
  export let labelText = null
  export let invalidText = ''

  const flatpickrOptions = {
    element: `#flatpickr_${Math.floor(Math.random() * 100)}`,
    allowInput: true,
  }
  options = { ...flatpickrOptions, ...options }
</script>

<Flatpickr {options} bind:value element={flatpickrOptions.element} on:change>
  <div class="flatpickr" id={flatpickrOptions.element.substring(1)}>
    <TextInput
      invalid={invalidText !== ''}
      {invalidText}
      {labelText}
      placeholder="Select Date.."
      data-input
    />
  </div>
</Flatpickr>
```

**Pull request closed without merging**
