### PR TITLE
add circle support

### PR DESCRIPTION
**Pull request by antony**

### CODE REVIEW

**Comment by antony** [comment]
I'll merge this asap :)

**Comment by jacobmischka** [comment]
I have done both already, you should have gotten some emails about it.

image

**Comment by antony** [comment]
Sorry, totally forgot about this for a while!

Sadly it still doesn't look like I'm able to add it to CircleCI. Not sure exactly what permissions are required.
Screenshot from 2019-05-22 10-07-07

**Comment by antony** [comment]
Btw I've just noticed that you have github actions enabled for this project, which is probably a better way to do this.

I'll close this in favour of that!

**Pull request closed without merging**
